---
#See https://hub.docker.com/r/portainer/agent for more info about the image.
#This template is made for "docker standalone" edge agent deployments. 
version: "3"

services:
  portainer_edge_agent:
    image: portainer/agent:2.18.3
    container_name: portainer_edge_agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - ./data:/data
    environment:
      #London is an example, change it to yours
      TZ: "Europe/London"
      #Portainer will tell you all of these env vars in the docker run command when you try to add a new environment
      #Is it an edge agent? 1 = yes, 0 = no
      EDGE: 1
      #Allow self signed certificates? 1 = yes, 0 = no
      EDGE_INSECURE_POLL: 0
      EDGE_ID: YOUR_ID_GOES_HERE
      EDGE_KEY: YOUR_TOKEN/KEY_GOES_HERE
