---
# Note that this template is supposed to be used to deploy an instance shared across multiple stacks
# See https://hub.docker.com/_/postgres for more info about the image
version: "3"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432 #you might want to move it to an expose section
    environment:
      #This is the password for "postgres" user
      POSTGRES_PASSWORD: "your-password-goes-here"
      #London is an example, change it to yours
      TZ: "Europe/London"
    volumes:
      - ./data:/var/lib/postgresql/data

