---
#See https://hub.docker.com/r/dbeaver/cloudbeaver for more info about the image.
#CloudBeaver Docker docs: https://github.com/dbeaver/cloudbeaver/wiki/Run-Docker-Container
#This template uses Community Edition
version: "3"

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - 8978:8978 # Web UI
    volumes:
      - ./workspace:/opt/cloudbeaver/workspace
    environment:
      #London is an example, change it to yours
      TZ: "Europe/London"  
